Repository FRONT-END-BOOTCAMP-PLUS-4/git-go, pull requests merged in 2025-05, with the labels that each got.

#6 Chore: 메인 폴더 삭제
  app/main/components/.gitkeep
  app/main/page.tsx
Labels: good first issue

#12 Feat: 깃허브 로그인
  app/api/auth/[...nextauth]/route.ts
  app/components/LoginWithGitHubButton.tsx
  app/page.tsx
  package-lock.json
  package.json
  public/github-login.svg
  types/next-auth.d.ts
Labels: enhancement, good first issue

#17 Feat: 회고록 작성 UI 생성
  .prettierrc
  app/(member)/[type]/memoir/components/AiSummary.tsx
  app/(member)/[type]/memoir/components/ChangeList.tsx
  app/(member)/[type]/memoir/components/CommitMemoir.tsx
  app/(member)/[type]/memoir/components/Editor.tsx
  app/(member)/[type]/memoir/components/FileList.tsx
  app/(member)/[type]/memoir/components/FileTree.tsx
  app/(member)/[type]/memoir/components/PullRequestMemoir.tsx
  app/(member)/[type]/memoir/page.tsx
  app/(member)/commit/[id]/page.tsx
  app/(member)/commits/[id]/page.tsx
  app/(member)/commits/components/.gitkeep
  app/(member)/commits/page.tsx
  app/(member)/memoirs/[id]/page.tsx
  app/(member)/memoirs/components/.gitkeep
  app/(member)/memoirs/page.tsx
  app/(member)/pull-request/[id]/page.tsx
  app/(member)/pull-requests/[id]/page.tsx
  app/(member)/pull-requests/components/.gitkeep
  app/(member)/pull-requests/page.tsx
  app/globals.css
  package-lock.json
  package.json
  prettier.config.js
  tsconfig.json
Labels: enhancement

#23 Feat: 로그인시 user테이블에 회원정보 추가할때 중복확인해서 없으면 추가 있으면 추가안함
  infra/repositories/prisma/PrUserRepository.ts
Labels: enhancement, P1

#25 Feat: 회원탈퇴 기능 추가
  app/api/auth/[...nextauth]/route.ts
  app/api/auth/withdraw/route.ts
  app/components/WithdrawButton.tsx
  application/usecase/user/WithdrawUser.ts
  domain/repositories/UserRepository.ts
  infra/repositories/prisma/PrUserRepository.ts
  types/next-auth.d.ts
Labels: enhancement, P2

#30 Feat: member/commits 커밋 목록 페이지 UI 작업 완료
  app/(member)/commits/components/.gitkeep
  app/(member)/commits/components/CommitCard.tsx
  app/(member)/commits/page.tsx
  app/globals.css
  app/layout.tsx
  public/file.svg
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
Labels: enhancement, P1

#39 Feat: 저장소추가 버튼 눌렀을 때 모달에서 이미 저장한 레포들 체크되어 나오는 기능 추가
  app/(member)/components/RepoSelectModal.tsx
  app/api/repos/user/route.ts
  application/usecase/repo/FindUserRepos.ts
  application/usecase/repo/dto/FindUserReposDto.ts
  domain/repositories/RepoRepository.ts
  infra/repositories/prisma/PrRepoRepository.ts
Labels: enhancement, P1

#41 Feat: member/layout.tsx UI 수정 작업
  app/(member)/[type]/memoir/page.tsx
  app/(member)/commits/[id]/page.tsx
  app/(member)/commits/page.tsx
  app/(member)/components/PageTab.tsx
  app/(member)/components/SideBar.tsx
  app/(member)/layout.tsx
  app/(member)/memoirs/components/Filter/CommitPrFilter.tsx
  app/(member)/memoirs/page.tsx
  app/(member)/pull-requests/[id]/page.tsx
  app/(member)/pull-requests/page.tsx
Labels: enhancement, P1

#42 Feat: 저장소추가 버튼 눌렀을 때 모달에서 연동하기 누를 때 이미 체크되어 있던 레포는 추가되지 않고 없어진건 삭제하는 기능 추가
  application/usecase/repo/SaveRepos.ts
  domain/repositories/RepoRepository.ts
  infra/repositories/prisma/PrRepoRepository.ts
Labels: enhancement, P1

#46 Feat: 커밋페이지에서 로그인한 유저가 연동한 레포가 없으면 저장소추가모달 뜨도록 구현
  app/(member)/commits/page.tsx
Labels: enhancement, P2

#47 Feat: commit 회고록 UI 수정
  app/(member)/[type]/memoir/components/AiSummary.tsx
  app/(member)/[type]/memoir/components/ChangeList.tsx
  app/(member)/[type]/memoir/components/CommitMemoir.tsx
  app/(member)/[type]/memoir/components/CreateMemoirLayout.tsx
  app/(member)/[type]/memoir/components/Editor.tsx
  app/(member)/[type]/memoir/components/FileList.tsx
  app/(member)/[type]/memoir/components/FileTree.tsx
  app/(member)/[type]/memoir/components/PullRequestMemoir.tsx
  app/(member)/[type]/memoir/components/Select.tsx
  app/components/Header.tsx
  app/globals.css
  hooks/useDeviceType.ts
  package-lock.json
  package.json
  types/CommitType.ts
Labels: enhancement

#49 Feat: 로그아웃 기능 추가
  app/components/LogoutButton.tsx
Labels: enhancement, P1

#57 Feat: Time Period 필터 추가
  app/(member)/components/SideBar.tsx
  app/(member)/components/TimeFilter.tsx
  store/useFilterStore.ts
Labels: enhancement, P1

#63 Feat: 사이드바에 내가 연동한 레포목록 나오도록 구현
  app/(member)/components/SideBar.tsx
Labels: enhancement, P1

#66 Feat: 내 회고록 페이지 UI 작업 완료
  app/(member)/components/SideBar.tsx
  app/components/LoginWithGitHubButton.tsx
  app/member/[type]/memoir/components/AiSummary.tsx
  app/member/[type]/memoir/components/ChangeList.tsx
  app/member/[type]/memoir/components/CommitMemoir.tsx
  app/member/[type]/memoir/components/CreateMemoirLayout.tsx
  app/member/[type]/memoir/components/Editor.tsx
  app/member/[type]/memoir/components/FileList.tsx
  app/member/[type]/memoir/components/FileTree.tsx
  app/member/[type]/memoir/components/PullRequestMemoir.tsx
  app/member/[type]/memoir/components/Select.tsx
  app/member/[type]/memoir/page.tsx
  app/member/commits/components/CommitCard.tsx
  app/member/commits/page.tsx
  app/member/components/PageTab.tsx
  app/member/components/RepoSelectModal.tsx
  app/member/components/SideBar.tsx
  app/member/components/TimeFilter.tsx
  app/member/layout.tsx
  app/member/memoirs/[id]/page.tsx
  app/member/memoirs/components/.gitkeep
  app/member/memoirs/components/Filter/CommitPrFilter.tsx
  app/member/memoirs/components/MemoirCard.tsx
  app/member/memoirs/page.tsx
  app/member/pull-requests/components/PrCard.tsx
  app/member/pull-requests/components/PrCommitCard.tsx
  app/member/pull-requests/page.tsx
  app/member/stats/components/.gitkeep
  app/member/stats/page.tsx
  constants/url.ts
  public/memoir-purple.svg
Labels: enhancement, P1

#75 Feat: 초기페이지에서 로그인하면 로그인버튼대신 “마이페이지”로 수정
  app/page.tsx
Labels: P2

#78 Feat: 통계 페이지 UI 작업
  app/member/stats/components/BottomCard.tsx
  app/member/stats/components/StatsCard.tsx
  app/member/stats/page.tsx
  public/activity.svg
Labels: enhancement, P1

#83 Feat: 로그인 안했을 때, member 페이지 접근 막기
  middleware.ts
Labels: enhancement, P2

#85 Feat: 통계페이지에서 레포별로 전체커밋 수 보여주는 기능 구현
  app/api/stats/commits/route.ts
  app/member/components/SideBar.tsx
  app/member/stats/page.tsx
  application/usecase/github/FetchCommitStats.ts
  application/usecase/github/dto/FetchCommitStatsDto.ts
  application/usecase/github/dto/ResponseCommitStatsDto.ts
  domain/repositories/StatsRepository.ts
  infra/repositories/github/GbStatsRepository.ts
  store/repoStore.ts
Labels: enhancement, P1

#93 Docs: README 작업
  README.md
Labels: documentation, P2

#95 Feat: 커밋 목록 페이지 기능 구현
  app/api/auth/[...nextauth]/route.ts
  app/api/github/commits/route.ts
  app/api/stats/memoirs/route.ts
  app/member/commits/components/CommitCard.tsx
  app/member/commits/page.tsx
  app/member/components/SideBar.tsx
  app/member/pull-requests/components/PrCard.tsx
  application/usecase/github/FetchCommitList.ts
  application/usecase/github/dto/GithubCommitListDto.ts
  application/usecase/memoir/dto/FetchMemoirCountDto.ts
  domain/entities/GithubCommitList.ts
  domain/repositories/GithubCommitListRepository.ts
  infra/repositories/github/GbCommitListRepository.ts
  prisma/migrations/20250519004603_delete_rules/migration.sql
  prisma/schema.prisma
  store/repoStore.ts
Labels: enhancement, P1

#97 Feat: 저장소추가 버튼 눌렀을 때 모달에서 체크되어 있는 레포 해제 동작 수정
  app/api/repos/save/route.ts
  app/member/components/RepoSelectModal.tsx
  application/usecase/repo/SaveRepos.ts
  application/usecase/repo/dto/SaveReposDto.ts
  domain/repositories/RepoRepository.ts
  infra/repositories/prisma/PrRepoRepository.ts
Labels: enhancement

#133 Chore: schema.prisma DB pull
  prisma/schema.prisma
Labels: enhancement, P3

#137 Fix : 통계페이지에서 작성한 회고록 레포 로그인한 사용자의 수만 나오는게 아니라 해당 레포에 대한 전체 회고록 수가 나오는 부분 수정하기
  app/api/stats/memoirs/route.ts
  application/usecase/memoir/FetchMemoirCountUsecase.ts
  application/usecase/memoir/dto/FetchMemoirCountDto.ts
  domain/repositories/MemoirRepository.ts
  infra/repositories/prisma/PrMemoirRepository.ts
Labels: bug

#140 fix: 통계페이지에서 커밋 하나도 없는 레포 통계 안나타나는 오류 해결하기
  infra/repositories/github/GbStatsRepository.ts
Labels: bug

#142 Feat: 회고록 조회, 수정 작업
  app/api/memoir/[id]/route.ts
  app/components/Header.tsx
  app/member/commits/[sha]/memoir/components/CommitMemoir.tsx
  app/member/components/CreateMemoir/EditorForm.tsx
  app/member/components/CreateMemoir/EditorFormReadOnly.tsx
  app/member/components/CreateMemoir/plate-editor/ui/plate-editor.tsx
  app/member/layout.tsx
  app/member/memoirs/[id]/page.tsx
  app/member/memoirs/commit/[id]/page.tsx
  app/member/memoirs/components/Detail/DetailMemoir.tsx
  app/member/memoirs/components/Detail/DetailMemoirLayout.tsx
  app/member/memoirs/components/MemoirCard.tsx
  app/member/memoirs/pull-request/[id]/page.tsx
  app/member/pull-requests/[pr_no]/memoir/components/PullRequestMemoir.tsx
  application/usecase/memoir/EditMemoirUsecase.ts
  application/usecase/memoir/GetMemoirUsecase.ts
  application/usecase/memoir/dto/EditMemoirDto.ts
  application/usecase/memoir/dto/GetMemoirDto.ts
  constants/url.ts
  domain/repositories/MemoirRepository.ts
  hooks/useCreateEditor.ts
  hooks/useMemoirForm.ts
  infra/repositories/prisma/PrMemoirRepository.ts
  types/memoir/Memoir.ts
Labels: enhancement, P1

#151 Feat: 회고목록페이지에서 회고의 내용 json 잘 처리하고 디자인 조정하기
  app/member/memoirs/components/MemoirCard.tsx
Labels: enhancement

#154 Feat: repoStore에 dbid도 추가하고 값 나오도록 구현
  app/member/components/SideBar.tsx
  store/repoStore.ts
Labels: enhancement

#157 Feat: 커밋 상세 내역 조회 API 완성
  app/api/github/commits/detail/route.ts
  app/member/commits/[sha]/memoir/components/CommitMemoir.tsx
  application/usecase/github/FetchCommitDetailUsecase.ts
  application/usecase/github/dto/GithubCommitDetailDto.ts
  domain/entities/GithubCommitDetail.ts
  domain/repositories/GithubCommitDetailRepository.ts
  infra/repositories/github/GbCommitDetailRepository.ts
  store/repoStore.ts
Labels: enhancement, P1

#160 Refactor: api route 변경 후, 적용
  app/api/memoir/route.ts
  app/api/memoirs/[id]/route.ts
  app/api/memoirs/route.ts
  app/member/components/CreateMemoir/EditorFormReadOnly.tsx
  app/member/memoirs/components/Detail/DetailMemoir.tsx
  app/member/memoirs/page.tsx
  hooks/useMemoirForm.ts
Labels: enhancement, P3

#161 Feat: 회고목록페이지에서 페이지네이션 구현하기
  app/api/memoirs/route.ts
  app/member/memoirs/components/MemoirCard.tsx
  app/member/memoirs/page.tsx
  app/member/pull-requests/components/PrCard.tsx
  application/usecase/memoir/GetMyMemoirsUsecase.ts
  domain/repositories/MemoirRepository.ts
  infra/repositories/prisma/PrMemoirRepository.ts
Labels: enhancement

#163 Prompt 수정
  app/member/components/CreateMemoir/AiSummary.tsx
  constants/aiPrompt.ts
Labels: good first issue, P3

#168 Feat: pr 회고록 작성, 조회 ui 완료
  app/member/commits/[sha]/memoir/components/CommitMemoir.tsx
  app/member/components/CreateMemoir/EditorForm.tsx
  app/member/components/CreateMemoir/plate-editor/ui/plate-editor.tsx
  app/member/memoirs/commit/[id]/page.tsx
  app/member/memoirs/components/Detail/CommitDetailMemoir.tsx
  app/member/memoirs/components/Detail/PullRequestDetailMemoir.tsx
  app/member/memoirs/components/MemoirCard.tsx
  app/member/memoirs/pull-request/[id]/page.tsx
  app/member/pull-requests/[pr_no]/memoir/components/PullRequestMemoir.tsx
  constants/mockPullRequests.ts
  hooks/useMemoirForm.ts
Labels: enhancement, P1

#171 Feat: 회고목록페이지에서 사이드바에 레포별로 내가 작성한 회고의 태그들 나오는 기능 구현하기
  app/api/memoirs/tags/route.ts
  app/member/components/SideBar.tsx
  application/usecase/memoir/GetMemoirTagsUsecase.ts
  domain/repositories/MemoirRepository.ts
  infra/repositories/prisma/PrMemoirRepository.ts
Labels: enhancement

#184 Feat: AI 요약 DB 저장
  app/member/commits/[sha]/memoir/components/CommitMemoir.tsx
  app/member/components/CreateMemoir/AiSummary.tsx
  constants/aiPrompt.ts
  hooks/useMemoirForm.ts
  store/AiSummaryStore.ts
Labels: enhancement, P2

#187 Feat: AI 요약 실제 데이터 연결
  app/member/commits/[sha]/memoir/components/CommitMemoir.tsx
  app/member/components/CreateMemoir/AiSummary.tsx
  hooks/useSimplifyCommitData.ts
Labels: enhancement, P1

#196 Feat: 회고목록페이지에서 이미 조회했을때 10분 이내로 다시 조회하면 다시 조회하지 않고 아까 조회했던 정보로 보여주는 기능 구현하기
  app/member/memoirs/page.tsx
Labels: enhancement

#202 Fix: 통계페이지에서 회원탈퇴 누르면 나오는 모달 위에 그래프가 나타나는 현상 수정
  app/member/stats/page.tsx
Labels: bug

#209 Fix: 통계페이지에서 통계 불러오는 중에 레포 바꾸면 통계 이상해지는 현상 수정
  app/member/stats/page.tsx
Labels: bug

#216 Chore: 통계페이지에서 커밋활동(최근7일) 에 그래프 나오기 전에 커밋정보없음 나오는 부분 ui수정
  app/member/stats/page.tsx
Labels: enhancement

#229 Release: 배포를 위한 테스트
  .vscode/settings.json
  app/api/auth/[...nextauth]/route.ts
  app/api/auth/authOptions.ts
  app/api/github/pull-requests/route.ts
  app/api/memoirs/[id]/route.ts
  app/components/Header.tsx
  app/favicon.ico
  app/layout.tsx
  app/member/commits/[sha]/memoir/components/CommitMemoir.tsx
  app/member/components/CreateMemoir/AiSummary.tsx
  app/member/components/CreateMemoir/CreateEditorForm.tsx
  app/member/components/CreateMemoir/EditEditorForm.tsx
  app/member/components/CreateMemoir/PullRequestAiSummary.tsx
  app/member/components/CreateMemoir/plate-editor/ui/emoji-input-element.tsx
  app/member/components/CreateMemoir/plate-editor/ui/plate-editor.tsx
  app/member/memoirs/components/Detail/CommitDetailMemoir.tsx
  app/member/memoirs/components/Detail/PullRequestDetailMemoir.tsx
  app/member/memoirs/page.tsx
  app/member/pull-requests/[pr_no]/memoir/components/PullRequestMemoir.tsx
  app/member/stats/page.tsx
  app/page.tsx
  application/usecase/github/FetchCommitDetailUsecase.ts
  application/usecase/github/FetchReposUsecase.ts
  application/usecase/github/dto/GithubCommitDetailDto.ts
  application/usecase/github/dto/GithubCommitListDto.ts
  constants/mockCommits.ts
  constants/mockPullRequests.ts
  eslint.config.mjs
  hooks/use-debounce.ts
  next.config.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: bug, P1

#237 Feat: 커밋 목록 불러오기 분기 처리 추가
  infra/repositories/github/GbCommitListRepository.ts
Labels: enhancement, P1

#252 Feat: 커밋 페이지 캐시 기능 추가
  app/member/commits/page.tsx
Labels: enhancement, P1

#272 Fix: 파일 명 넘어가는 현상 수정
  app/member/components/CreateMemoir/ChangeList.tsx
Labels: bug, P2

#277 Feat: 설정페이지에서 커밋가져오기설정 불러오기 전에 로딩페이지 나타나도록 수정
  app/member/components/CreateMemoir/plate-editor/ui/export-toolbar-button.tsx
  app/member/settings/page.tsx
  app/member/stats/components/SettingsSkeleton.tsx
Labels: enhancement

#295 Style: pretendard 폰트 적용
  app/layout.tsx
  app/member/components/CreateMemoir/plate-editor/ui/export-toolbar-button.tsx
  static/fonts/PretendardVariable.woff2
Labels: P2

#297 Chore: 저장소 추가할때 정렬기준, 사이드바에서 저장소 정렬기준 추가
  app/member/components/RepoSelectModal.tsx
  app/member/components/SideBar.tsx
Labels: enhancement
