Repository FRONT-END-BOOTCAMP-PLUS-4/git-go, pull requests merged in 2025-06, with the labels that each got.

#322 Feat: 회고록목록페이지에서 레포이름대신 커밋이나 PR제목 보여주도록 수정
  app/member/memoirs/components/MemoirCard.tsx
  application/usecase/memoir/dto/MemoirListDto.ts
Labels: enhancement

#325 Chore: 회고록목록페이지에서 커밋이나 PR제목 보여줄때 조건에 맞는 아이콘으로 보여주도록 수정
  app/member/memoirs/components/MemoirCard.tsx
Labels: enhancement

#329 Chore: 사이드바에서 연동한 저장소가 없을 경우 빈공간 대신 문구로 나오도록 수정
  app/member/components/SideBar.tsx
Labels: enhancement

#345 Feat: 404페이지 추가
  app/not-found.tsx
  public/404.png
Labels: enhancement

#355 Chore: 저장소추가 모달 날짜형식 수정
  app/member/components/RepoSelectModal.tsx
Labels: enhancement

#357 Fix: 저장소 연동 없는 경우, 내 회고록 빈 목록 표시
  app/member/memoirs/page.tsx
Labels: bug, P1

#364 Fix: theme값 없을 시, export 할 경우 기본값 흰색으로 변경
  app/member/components/CreateMemoir/plate-editor/ui/export-toolbar-button.tsx
Labels: bug, P2

#367 Feat: 저장소 모달 수정(체크된 저장소가 처음에 맨위로 나오게 수정)
  app/member/components/RepoSelectModal.tsx
Labels: enhancement

#382 Fix: 소유권 확인을 위한 html 파일 추가
  public/googlefb1e0c2a7945e170.html
Labels: bug, good first issue, P3

#376 Feat: 랜딩 페이지 모바일 버전 추가
  app/components/ScrollControls.tsx
  app/page.tsx
Labels: enhancement, P2
